"""empty message

Revision ID: b56ad6d1ca3
Revises: 490875df28b
Create Date: 2015-11-22 01:52:58.359168

"""

# revision identifiers, used by Alembic.
revision = 'b56ad6d1ca3'
down_revision = '490875df28b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_all', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'results_pkey')
    )
    ### end Alembic commands ###
